BlogApp/Controllers/CreateArticlesController.cs
using BlogApp.Data;
using BlogApp.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using System.Text.Json;
using System.IO;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;

namespace BlogApp.Controllers
{
    public class CreateArticlesController : Controller
    {

        private readonly ApplicationDbContext _context;

        [Obsolete]
        private Microsoft.AspNetCore.Hosting.IHostingEnvironment Environment;

        [Obsolete]
        public CreateArticlesController(ApplicationDbContext context, Microsoft.AspNetCore.Hosting.IHostingEnvironment _environment)
        {
            _context = context;
            Environment = _environment;
        }

        public IActionResult CreateNewArticle(int id)
        {
            if(id == 0) { return View(); }
            else
            {
                var articleDetails = _context.AllArticles.Find(id);

                var articletoedit = new ArticleToCreate
                {
                    ArticleTitle = articleDetails.ArticleTitle,
                    ArticleId = articleDetails.ArticleId,
                    ArticleContent = articleDetails.ArticleContent,
                    ArticleCategory = articleDetails.ArticleCategory,
                    ArticleCreatedDate = articleDetails.ArticleCreatedDate,
                    ArticleDeletedDate = articleDetails.ArticleDeletedDate,
                    IsArticleDeleted = articleDetails.IsArticleDeleted
                };


                return View(articletoedit);
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Obsolete]
        public IActionResult CreateNewArticle(ArticleToCreate articleobj, bool updatemode)
        {
            string thumbnailfileName = "";
            if (ModelState.IsValid)
            {
                var contentList = JsonSerializer.Deserialize<IList<ArticleContent>>(articleobj.ArticleContent);

                // saving thumbnail
                if(articleobj.ArticleThumbNail != null)
                {
                    string thumbnailpath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/images");

                    //create folder if not exist
                    if (!Directory.Exists(thumbnailpath))
                        Directory.CreateDirectory(thumbnailpath);

                    FileInfo thumbnailfileInfo = new FileInfo(articleobj.ArticleThumbNail.FileName);
                    thumbnailfileName = articleobj.ArticleTitle.ToString().Replace(" ", "_") + "_thumbnail" + thumbnailfileInfo.Extension;

                    string thumbnailfileNameWithPath = Path.Combine(thumbnailpath, thumbnailfileName);

                    using (var stream = new FileStream(thumbnailfileNameWithPath, FileMode.Create))
                    {
                        articleobj.ArticleThumbNail.CopyTo(stream);
                    }
                }
                // saving thumbnail


                foreach (var content in contentList)
                {
                    if(content.element_type == "image")
                    {
                        var base64index = content.image_base64.IndexOf("base64,") + 7;
                        byte[] imagebytes = Convert.FromBase64String((content.image_base64.Substring(base64index)));
                        string path = Path.Combine(Environment.WebRootPath, "images");
                        if (!Directory.Exists(path))
                        {
                            Directory.CreateDirectory(path);
                        }
                        var fileName = articleobj.ArticleTitle.ToString().Replace(" ","_") + "_" + content.content_id.ToString() + "." + content.image_type;

                        var filePath = Path.Combine(path, fileName);

                        var contents = new StreamContent(new MemoryStream(imagebytes));

                        using (FileStream fs = System.IO.File.Create(filePath))

                        {

                            contents.CopyToAsync(fs);

                        }

                        content.image_base64 = fileName;

                    }
                }

                articleobj.ArticleContent = JsonSerializer.Serialize(contentList);

                if (!updatemode)
                {
                    _context.AllArticles.Add(new Article 
                    { 
                    ArticleTitle = articleobj.ArticleTitle,
                    ArticleCategory = articleobj.ArticleCategory,
                    ArticleContent = articleobj.ArticleContent,
                    ArticleCreatedDate = articleobj.ArticleCreatedDate,
                    ArticleDeletedDate = articleobj.ArticleDeletedDate,
                    ArticleId = articleobj.ArticleId,
                    ArticleThumbNail = thumbnailfileName,
                    IsArticleDeleted = articleobj.IsArticleDeleted
                    });
                }
                else
                {
                    _context.AllArticles.Update(new Article
                    {
                        ArticleTitle = articleobj.ArticleTitle,
                        ArticleCategory = articleobj.ArticleCategory,
                        ArticleContent = articleobj.ArticleContent,
                        ArticleCreatedDate = articleobj.ArticleCreatedDate,
                        ArticleDeletedDate = articleobj.ArticleDeletedDate,
                        ArticleId = articleobj.ArticleId,
                        ArticleThumbNail = thumbnailfileName,
                        IsArticleDeleted = articleobj.IsArticleDeleted
                    });
                }

                _context.SaveChanges();
                TempData["ResultOk"] = "Record Added Successfully !";
                return RedirectToAction("CreateNewArticle");
            }
            else
            {
                return View(articleobj);

            }
        }
    }
}

BlogApp/Controllers/ShowArticlesController.cs
using BlogApp.Data;
using Microsoft.AspNetCore.Mvc;
using BlogApp.Models;

namespace BlogApp.Controllers
{
    public class ShowArticlesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ShowArticlesController(ApplicationDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public JsonResult GetAll()
        {
            int totalRecord = 0;
            int filterRecord = 0;
            var draw = Request.Form["draw"].FirstOrDefault();
            var sortColumn = Request.Form["columns[" + Request.Form["order[0][column]"].FirstOrDefault() + "][name]"].FirstOrDefault();
            var sortColumnDirection = Request.Form["order[0][dir]"].FirstOrDefault();
            var searchValue = Request.Form["search[value]"].FirstOrDefault();
            int pageSize = Convert.ToInt32(Request.Form["length"].FirstOrDefault() ?? "0");
            int skip = Convert.ToInt32(Request.Form["start"].FirstOrDefault() ?? "0");
            var data = _context.Set<Article>().AsQueryable();
            //get total count of data in table
            totalRecord = data.Count();
            // search data when search value found
            if (!string.IsNullOrEmpty(searchValue))
            {
                data = data.Where(x => x.ArticleTitle.ToLower().Contains(searchValue.ToLower()) || x.ArticleCategory.ToString().ToLower().Contains(searchValue.ToLower()));
            }
            // get total count of records after search
            filterRecord = data.Count();
            //sort data
            // if (!string.IsNullOrEmpty(sortColumn) && !string.IsNullOrEmpty(sortColumnDirection)) data = data.OrderBy(sortColumn, sortColumnDirection);
            //pagination
            var articlesList = data.Skip(skip).Take(pageSize).ToList();
            var returnObj = new
            {
                draw = draw,
                recordsTotal = totalRecord,
                recordsFiltered = filterRecord,
                data = articlesList
            };

            return Json(returnObj);
        }
    }

}

BlogApp/Controllers/ViewArticleController.cs
using BlogApp.Data;
using BlogApp.Models;
using Microsoft.AspNetCore.Mvc;
using System.Text.Json;

namespace BlogApp.Controllers
{
    public class ViewArticleController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ViewArticleController(ApplicationDbContext context)
        {
            _context = context;
        }

        public IActionResult Index(int id)
        {
            var articleDetails = _context.AllArticles.Find(id);
            //var contentList = JsonSerializer.Deserialize<IList<ArticleContent>>(articleDetails.ArticleContent);
            return View(articleDetails);
        }
    }
}

BlogApp/Views/ShowArticles/Index.cshtml
<head>
    <link href="~/lib/datatables/datatables.min.css" rel="stylesheet" />
</head>

<div class="container">
    <div class="table-responsive">
        <table id="ArticlesTable" class="table table-bordered">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Title</th>
                    <th>Article Content</th>
                    <th>Category</th>
                    <th>Created date</th>
                </tr>
            </thead>
        </table>
    </div>
</div>


                   @section Scripts{
    <script src="~/lib/datatables/datatables.min.js"></script>
    <script>
        $(document).ready(function () {
           $('#ArticlesTable').DataTable(
               {
                   ajax: {
                       url: "ShowArticles/GetAll",
                       type: "POST",
                   },
                   processing: true,
                   serverSide: true,
                   filter: true,
                   columns: [
                       { 
                           data: "articleId", 
                           name: "ArticleId",
                           render: function (data, type) {
 
                                if (type === 'display') {
 
                                    return '<a onclick="editContent(' + data + ')" id="article_' + data + '" value=' + data + '><i class="fa fa-edit" style="font-size:15px;"></i></a>';
                                }
 
                                return data;
                            }
                       
                       
                       },
                       { 
                           data: "articleTitle", 
                           name: "ArticleTitle",
                           render: function (data, type, row) {
 
                                if (type === 'display') {
 
                                    return "<button class='btn btn-link btn-sm' onclick='openThisPage(" + row.articleId + ")'>" + row.articleTitle + "</button>";
                                }
 
                                return data;
                            }
                       
                       },
                       { 
                           data: "articleContent", 
                           name: "ArticleContent",
                           visible: false
                       },
                       { data: "articleCategory", name: "ArticleCategory" },
                       { data: "articleCreatedDate", name: "ArticleCreatedDate" }
                   ]
               }
           );
       });

       function openThisPage(articleId){
           console.log(articleId, "articleId");
            var url = '@Url.Action("Index", "ViewArticle", new { id = "__id__" })';
            window.location.href = url.replace('__id__', articleId);       }

        function editContent(articleId) {
            console.log(articleId, "articleId");
            var url = '@Url.Action("CreateNewArticle", "CreateArticles", new { id = "__id__" })';
            window.location.href = url.replace('__id__', articleId);
        }

    </script>
}